web:
        image: grayzone/screening
        command: /go/src/github.com/grayzone/screening/screening; sleep 10000
        ports:
                - "80:8080"         
        links:
                - postgresql
postgresql:
        image: grayzone/postgresql
        environment: 
                DB_PASS: 123456
                DB_USER: screening
                DB_NAME: screening
