web:
        image: grayzone/screening
        ports:
                - "80:8080"         
        links:
                - postgresql
postgresql:
        image: grayzone/postgresql
        volumes:
                - /var/lib/pgsql/data